require('dotenv').config();
const express = require('express');
const axios = require('axios');
const cors = require('cors');
const helmet = require('helmet');
const morgan = require('morgan');
const app = express();
const cache = new Map();
app.use(helmet());
app.use(cors({ origin: process.env.ALLOWED_ORIGINS?.split(',') || '*', credentials: true }));
app.use(express.json());
if (process.env.NODE_ENV === 'development') app.use(morgan('dev'));
const fetchImages = async destination => { const key = destination.trim().toLowerCase(); const cached = cache.get(key); if (cached && cached.expiresAt > Date.now()) return { ...cached.data, fromCache: true }; try { const response = await axios.get('https://commons.wikimedia.org/w/api.php', { params: { action: 'query', format: 'json', generator: 'search', gsrsearch: `${destination} India`, gsrnamespace: 6, gsrlimit: 8, prop: 'imageinfo', iiprop: 'url|size', iiurlwidth: 800 }, timeout: 5000 }); const pages = Object.values(response.data?.query?.pages || {}); const images = pages.filter(page => page.imageinfo?.[0]).map(page => ({ url: page.imageinfo[0].thumburl || page.imageinfo[0].url, thumbnail: page.imageinfo[0].thumburl || page.imageinfo[0].url, source: 'wikimedia', alt: page.title?.replace('File:', '') || `${destination} travel photo` })); const data = { success: true, destination, images, source: 'wikimedia', timestamp: new Date().toISOString() }; cache.set(key, { data, expiresAt: Date.now() + 86400000 }); return data; } catch (error) { return { success: false, destination, images: [], source: 'fallback', message: 'Unable to fetch images at this time' }; } };
app.get('/', (req, res) => res.json({ success: true, service: 'image-service', version: '1.0.0' }));
app.get('/health', (req, res) => res.json({ success: true, service: 'image-service', provider: 'wikimedia', timestamp: new Date().toISOString() }));
app.get('/api/images/destination/:destination', async (req, res) => res.json(await fetchImages(req.params.destination)));
app.get('/api/images/search', async (req, res) => { const query = req.query.q || req.query.query; if (!query) return res.status(400).json({ success: false, message: 'q or query is required' }); res.json(await fetchImages(query)); });
app.post('/api/images/destinations', async (req, res) => { const { destinations } = req.body; if (!Array.isArray(destinations) || !destinations.length || destinations.length > 10) return res.status(400).json({ success: false, message: 'destinations must contain 1 to 10 items' }); const results = await Promise.all(destinations.map(fetchImages)); res.json({ success: true, count: results.length, destinations: Object.fromEntries(results.map(result => [result.destination, result])) }); });
app.get('/api/images/cache/stats', (req, res) => res.json({ success: true, cacheEntries: cache.size }));
app.delete('/api/images/cache', (req, res) => { const cleared = cache.size; cache.clear(); res.json({ success: true, cleared }); });
app.use((req, res) => res.status(404).json({ success: false, message: 'Route not found' }));
app.listen(process.env.PORT || 5007, () => console.log(`Image Service running on port ${process.env.PORT || 5007}`));
